### ISSUE TITLE
Create sign in functionality 

### ISSUE THREAD

**Issue by krod02** [DevByDJ/Database-Engineering-Project#22]
- create event handler on sign in click 
- function will validate user email and password
- if user found direct to dashboard page
- user validation will probably be done through a query in database entity student looking for their username and password
- password does not need to be integrated for project submission

**Comment by krod02** [comment]
implement catch error if sign info is incorrect

**Comment by DevByDJ** [comment]
@krod02 Added in Pull Request #30
